### ISSUE TITLE
Won’t load wav file

### ISSUE THREAD

**Issue by silversurfer678** [morevnaproject-org/papagayo-ng#119]
Hello, 
I just installed Papagayo-Ng 1.6.6.0 on a windows 10 pro machine. I created a quick test .wav file using audacity, 16 bit pcm. Tried to open it in papagayo Ng and nothing happens, doesn’t load, doesn’t do anything? Please help

thanks

**Comment by steveway** [comment]
There should be an option that allows you to download FFmpeg for Papagayo-NG.
Did you do that already?
If not then the supported file types will be limited.
If this still does not work even with FFmpeg in place then please upload that file here so we can try to reproduce it.

**Comment by AlexPelmen** [comment]
I have the same problem

Traceback (most recent call last):
  File "C:\Program Files (x86)\Papagayo-NG\papagayo-ng\SoundPlayer.py", line 48, in __init__
    self.wave_reference = wave.open(self.soundfile)
  File "C:\Program Files (x86)\Papagayo-NG\lib\wave.py", line 498, in open
    return Wave_read(f)
  File "C:\Program Files (x86)\Papagayo-NG\lib\wave.py", line 163, in __init__
    self.initfp(f)
  File "C:\Program Files (x86)\Papagayo-NG\lib\wave.py", line 130, in initfp
    raise Error, 'file does not start with RIFF id'
Error: file does not start with RIFF id

File that I tried to load https://drive.google.com/file/d/18F1sTEwikpV15JS1nQcu11uIK0uus5Y6/view?usp=sharing
... and not only that file. Also I tried to load wav, mp3, m4a
I have ffmpeg on PC

**Comment by AlexPelmen** [comment]
I found that there is another error text, when I load wav file. So solution was to convert .wav file to 16 bit (also maybe to Pydub formats 8 and 32 bits). Just after convertation the file was loaded.

If someone has the same issue, use ffmpeg command to convert file to 16bit
```bash
ffmpeg -i input.wav -ar 48000 -ac 2 -acodec pcm_s16le output.wav
```

**Comment by ogallagher** [comment]
> Hello, I just installed Papagayo-Ng 1.6.6.0 on a windows 10 pro machine. I created a quick test .wav file using audacity, 16 bit pcm. Tried to open it in papagayo Ng and nothing happens, doesn’t load, doesn’t do anything? Please help

@steveway @silversurfer678 Might it be because speech to text detection is being attempted on audio file load, and if no speech is detected in the audio, then the empty result is not handled correctly? That was something I found when doing my own testing, and have included a fix in my PR #124

**Comment by luzpaz** [comment]
Is this still relevant ?
