### ISSUE TITLE
Cannot download Rhubarb in-app

### ISSUE THREAD

**Issue by dimitritholen** [morevnaproject-org/papagayo-ng#120]
Using Papagayo-NG 1.6.6.0

When I click "Download Rhubarb" in the toolbar, I get the following error:

```
Traceback (most recent call last):
  File "utilities.py", line 196, in run
  File "LipsyncFrameQT.py", line 473, in download_rhubarb
  File "urllib\request.py", line 214, in urlopen
  File "urllib\request.py", line 501, in open
  File "urllib\request.py", line 320, in __init__
  File "urllib\request.py", line 346, in full_url
  File "urllib\request.py", line 375, in _parse
ValueError: unknown url type: ''
```

**Comment by dimitritholen** [comment]
Sorry, this happens in a fork.
