### ISSUE TITLE
Download Rhubarb: Unknow url type: ' '

### ISSUE THREAD

**Issue by PhilDevProg** [morevnaproject-org/papagayo-ng#121]
I'm using Fedora 36 and I'm running PapagayoNG from the master branch and when I click on the 'Download Rhubarb' button I get this error:
```
Traceback (most recent call last):
  File "/home/.../.../papagayo-ng/utilities.py", line 196, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/.../.../papagayo-ng/LipsyncFrameQT.py", line 473, in download_rhubarb
    with urllib.request.urlopen(release_url) as req:
  File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib64/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib64/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib64/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

**Comment by steveway** [comment]
Hi, I fixed that problem earlier in June.
Try the current version from my branch, or just the changes from that one commit:
https://github.com/steveway/papagayo-ng

**Comment by luzpaz** [comment]
Can this issue be closed ?
