### ISSUE TITLE
Program will not start from latest source code

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#85]
Trying to run from source code, i get the following errors

`K:\Programs\papagayo-ng-master>python papagayo-ng.py
Traceback (most recent call last):
  File "papagayo-ng.py", line 4, in <module>
    import LipsyncFrameQT

  File "K:\Programs\papagayo-ng-master\LipsyncFrameQT.py", line 40, in <module>
    from WaveformViewRewrite import WaveformView

  File "K:\P38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "K:\Programs\papagayo-ng-master\WaveformViewRewrite.py", line 28, in <module>
    import numpy as np

  File "K:\P38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "K:\P38\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init

  File "K:\P38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

  File "K:\P38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))

  File "K:\P38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application`

Thank you

**Comment by steveway** [comment]
Hi, are you sure that numpy is working correctly on your machine?
If you import numpy on an interactive python session does that work?

**Comment by Hunanbean** [comment]
Sincere apologies for the long delay in reply. 
I reinstalled my python, and the requirements. It is working as expected.

Thank you
