### ISSUE TITLE
audioread ModuleNotFoundError

### ISSUE THREAD

**Issue by SimplSam** [morevnaproject-org/papagayo-ng#93]
Just a note. When I ran this source version it failed due to 'audioread' not found, and the 'audioread' package is not in the requirements.txt list.

`python papagayo-ng.py`
```
Traceback (most recent call last):
  File "P:\_Dev\_OPP\papagayo-ng-master-clean\papagayo-ng.py", line 4, in <module>
    import LipsyncFrameQT
  File "P:\_Dev\_OPP\papagayo-ng-master-clean\LipsyncFrameQT.py", line 40, in <module>
    from WaveformViewRewrite import WaveformView
  File "C:\Apps\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "P:\_Dev\_OPP\papagayo-ng-master-clean\WaveformViewRewrite.py", line 32, in <module>
    from LipsyncDoc import *
  File "C:\Apps\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "P:\_Dev\_OPP\papagayo-ng-master-clean\LipsyncDoc.py", line 40, in <module>
    import SoundPlayerNew as SoundPlayer
  File "C:\Apps\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "P:\_Dev\_OPP\papagayo-ng-master-clean\SoundPlayerNew.py", line 4, in <module>
    import audioread
  File "C:\Apps\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'audioread'
```

fixed with: pip install audioread

**Comment by steveway** [comment]
Ah yes, that is correct. I'll fix that.

**Comment by steveway** [comment]
Should be fixed in https://github.com/morevnaproject-org/papagayo-ng/pull/94
